/**
 * Beauty_Pro - Products API
 */

import { connectDB } from '@/lib/db';
import Product from '@/models/Product';

export const dynamic = 'force-dynamic';

// Maps each demo product to its local product image (generated by scripts/create-product-images.js)
const productImageMap = {
  // SKINCARE
  'demo-sk-01': '/images/products/skincare-serum.svg',
  'demo-sk-02': '/images/products/skincare-cream.svg',
  'demo-sk-03': '/images/products/skincare-mist.svg',
  'demo-sk-04': '/images/products/skincare-cleanser.svg',
  'demo-sk-05': '/images/products/skincare-moisturizer.svg',
  'demo-sk-06': '/images/products/skincare-sunscreen.svg',
  'demo-sk-07': '/images/products/skincare-vitamin-c.svg',
  'demo-sk-08': '/images/products/skincare-toner.svg',
  'demo-sk-09': '/images/products/skincare-eye-cream.svg',
  'demo-sk-10': '/images/products/skincare-face-wash.svg',
  'demo-sk-11': '/images/products/skincare-night-cream.svg',
  'demo-sk-12': '/images/products/skincare-mask.svg',
  // MAKEUP
  'demo-mk-01': '/images/products/makeup-lipstick.svg',
  'demo-mk-02': '/images/products/makeup-foundation.svg',
  'demo-mk-03': '/images/products/makeup-eyeshadow.svg',
  'demo-mk-04': '/images/products/makeup-blush.svg',
  'demo-mk-05': '/images/products/makeup-mascara.svg',
  'demo-mk-06': '/images/products/makeup-highlighter.svg',
  'demo-mk-07': '/images/products/makeup-primer.svg',
  'demo-mk-08': '/images/products/makeup-concealer.svg',
  'demo-mk-09': '/images/products/makeup-lip-gloss.svg',
  'demo-mk-10': '/images/products/makeup-brow.svg',
  'demo-mk-11': '/images/products/makeup-setting-spray.svg',
  'demo-mk-12': '/images/products/makeup-contour.svg',
  // HAIRCARE
  'demo-hc-01': '/images/products/haircare-oil.svg',
  'demo-hc-02': '/images/products/haircare-shampoo.svg',
  'demo-hc-03': '/images/products/haircare-conditioner.svg',
  'demo-hc-04': '/images/products/haircare-serum.svg',
  'demo-hc-05': '/images/products/haircare-mask.svg',
  'demo-hc-06': '/images/products/haircare-spray.svg',
  'demo-hc-07': '/images/products/haircare-leave-in.svg',
  'demo-hc-08': '/images/products/haircare-dry-shampoo.svg',
  'demo-hc-09': '/images/products/haircare-hair-cream.svg',
  'demo-hc-10': '/images/products/haircare-scalp-treatment.svg',
  // FRAGRANCE
  'demo-fr-01': '/images/products/fragrance-mist.svg',
  'demo-fr-02': '/images/products/fragrance-perfume.svg',
  'demo-fr-03': '/images/products/fragrance-body-spray.svg',
  'demo-fr-04': '/images/products/fragrance-deodorant.svg',
  'demo-fr-05': '/images/products/fragrance-candle.svg',
  'demo-fr-06': '/images/products/fragrance-gift-set.svg',
  'demo-fr-07': '/images/products/fragrance-rose-perfume.svg',
  'demo-fr-08': '/images/products/fragrance-oud-oil.svg',
  'demo-fr-09': '/images/products/fragrance-lavender.svg',
  'demo-fr-10': '/images/products/fragrance-jasmine.svg',
  // BODY CARE
  'demo-bc-01': '/images/products/body-care-lotion.svg',
  'demo-bc-02': '/images/products/body-care-scrub.svg',
  'demo-bc-03': '/images/products/body-care-butter.svg',
  'demo-bc-04': '/images/products/body-care-oil.svg',
  'demo-bc-05': '/images/products/body-care-soap.svg',
  'demo-bc-06': '/images/products/body-care-cream.svg',
  'demo-bc-07': '/images/products/body-care-shower-gel.svg',
  'demo-bc-08': '/images/products/body-care-bath-bomb.svg',
  'demo-bc-09': '/images/products/body-care-foot-cream.svg',
  'demo-bc-10': '/images/products/body-care-massage-oil.svg',
};

const demoProducts = [
  // ===== SKINCARE (12 products) =====
  { _id: 'demo-sk-01', slug: 'rose-gold-radiance-serum', name: 'Rose Gold Radiance Serum', category: 'skincare', price: 3499, originalPrice: 4999, badge: 'Best Seller', rating: 4.8, reviewCount: 124, variants: ['30ml','50ml'], description: '24k gold serum for radiant skin.', images: [{ url: productImageMap['demo-sk-01'], alt: 'Rose Gold Radiance Serum', isPrimary: true }], inStock: true, benefits: ['Deep hydration', 'Anti-aging', 'Brightening'] },
  { _id: 'demo-sk-02', slug: 'diamond-radiance-cream', name: 'Diamond Radiance Cream', category: 'skincare', price: 4999, originalPrice: 5999, badge: 'Exclusive', rating: 4.9, reviewCount: 210, variants: ['50ml'], description: 'Diamond-infused luxury moisturizer.', images: [{ url: productImageMap['demo-sk-02'], alt: 'Diamond Radiance Cream', isPrimary: true }], inStock: true, benefits: ['Intense hydration', 'Anti-aging'] },
  { _id: 'demo-sk-03', slug: 'midnight-recovery-oil', name: 'Midnight Recovery Oil', category: 'skincare', price: 3799, originalPrice: 4299, badge: 'Best Seller', rating: 4.7, reviewCount: 145, variants: ['30ml'], description: 'Overnight rejuvenation oil.', images: [{ url: productImageMap['demo-sk-03'], alt: 'Midnight Recovery Oil', isPrimary: true }], inStock: true, benefits: ['Overnight repair', 'Nourishes skin'] },
  { _id: 'demo-sk-04', slug: 'gentle-foaming-cleanser', name: 'Gentle Foaming Cleanser', category: 'skincare', price: 1599, originalPrice: 1999, rating: 4.6, reviewCount: 89, variants: ['100ml','200ml'], description: 'Gentle daily cleanser for all skin types.', images: [{ url: productImageMap['demo-sk-04'], alt: 'Gentle Foaming Cleanser', isPrimary: true }], inStock: true, benefits: ['Deep cleanses', 'Gentle formula'] },
  { _id: 'demo-sk-05', slug: 'hydra-boost-moisturizer', name: 'Hydra Boost Moisturizer', category: 'skincare', price: 2499, originalPrice: 2999, rating: 4.7, reviewCount: 156, variants: ['50ml','100ml'], description: '24-hour hydration moisturizer.', images: [{ url: productImageMap['demo-sk-05'], alt: 'Hydra Boost Moisturizer', isPrimary: true }], inStock: true, benefits: ['24hr hydration', 'Non-greasy'] },
  { _id: 'demo-sk-06', slug: 'daily-defense-spf-50', name: 'Daily Defense SPF 50', category: 'skincare', price: 1899, originalPrice: 2199, rating: 4.8, reviewCount: 98, variants: ['50ml','100ml'], description: 'Broad spectrum SPF 50 protection.', images: [{ url: productImageMap['demo-sk-06'], alt: 'Daily Defense SPF 50', isPrimary: true }], inStock: true, benefits: ['SPF 50', 'Lightweight'] },
  { _id: 'demo-sk-07', slug: 'vitamin-c-brightening-serum', name: 'Vitamin C Brightening Serum', category: 'skincare', price: 2899, originalPrice: 3499, badge: 'New', rating: 4.6, reviewCount: 67, variants: ['30ml'], description: 'Brightening vitamin C serum with hyaluronic acid.', images: [{ url: productImageMap['demo-sk-07'], alt: 'Vitamin C Brightening Serum', isPrimary: true }], inStock: true, benefits: ['Brightens', 'Even tone'] },
  { _id: 'demo-sk-08', slug: 'rose-petal-toner', name: 'Rose Petal Toner Mist', category: 'skincare', price: 1299, originalPrice: 1599, rating: 4.4, reviewCount: 56, variants: ['100ml','200ml'], description: 'Hydrating rose water toner.', images: [{ url: productImageMap['demo-sk-08'], alt: 'Rose Petal Toner', isPrimary: true }], inStock: true, benefits: ['Hydrates', 'Refreshes'] },
  { _id: 'demo-sk-09', slug: 'golden-eye-cream', name: 'Golden Eye Cream', category: 'skincare', price: 3299, originalPrice: 3999, rating: 4.5, reviewCount: 78, variants: ['15ml','30ml'], description: 'Luxury eye cream with gold particles.', images: [{ url: productImageMap['demo-sk-09'], alt: 'Golden Eye Cream', isPrimary: true }], inStock: true, benefits: ['Reduces puffiness', 'Anti-aging'] },
  { _id: 'demo-sk-10', slug: 'gentle-face-wash', name: 'Gentle Face Wash', category: 'skincare', price: 999, originalPrice: 1299, badge: 'Sale', rating: 4.3, reviewCount: 112, variants: ['100ml','200ml'], description: 'Mild daily face wash for all skin types.', images: [{ url: productImageMap['demo-sk-10'], alt: 'Gentle Face Wash', isPrimary: true }], inStock: true, benefits: ['Gentle cleanse', 'pH balanced'] },
  { _id: 'demo-sk-11', slug: 'luxe-night-cream', name: 'Luxe Night Cream', category: 'skincare', price: 4499, originalPrice: 5499, badge: 'Exclusive', rating: 4.8, reviewCount: 89, variants: ['50ml'], description: 'Rich overnight night cream with retinol.', images: [{ url: productImageMap['demo-sk-11'], alt: 'Luxe Night Cream', isPrimary: true }], inStock: true, benefits: ['Repairs overnight', 'Anti-aging'] },
  { _id: 'demo-sk-12', slug: 'glow-sheet-mask', name: 'Glow Sheet Mask Pack', category: 'skincare', price: 699, originalPrice: 899, rating: 4.4, reviewCount: 145, variants: ['Pack of 5','Pack of 10'], description: 'Hydrating sheet mask for instant glow.', images: [{ url: productImageMap['demo-sk-12'], alt: 'Glow Sheet Mask', isPrimary: true }], inStock: true, benefits: ['Instant glow', 'Hydrates'] },
  // ===== MAKEUP (12 products) =====
  { _id: 'demo-mk-01', slug: 'velvet-matte-lipstick', name: 'Velvet Matte Lipstick', category: 'makeup', price: 2499, originalPrice: 2999, badge: 'New', rating: 4.6, reviewCount: 89, variants: ['Classic Red','Nude Pink','Berry'], description: 'Long-wear matte lipstick.', images: [{ url: productImageMap['demo-mk-01'], alt: 'Velvet Matte Lipstick', isPrimary: true }], inStock: true, benefits: ['16hr wear', 'Intense color'] },
  { _id: 'demo-mk-02', slug: 'glow-foundation', name: 'Glow Foundation SPF 25', category: 'makeup', price: 2799, originalPrice: 3199, rating: 4.3, reviewCount: 92, variants: ['Light','Medium','Warm'], description: 'Dewy foundation with SPF 25.', images: [{ url: productImageMap['demo-mk-02'], alt: 'Glow Foundation', isPrimary: true }], inStock: true, benefits: ['Dewy finish', 'SPF 25'] },
  { _id: 'demo-mk-03', slug: 'smoky-eye-palette', name: 'Smoky Eye Palette', category: 'makeup', price: 3999, originalPrice: 4499, badge: 'Best Seller', rating: 4.8, reviewCount: 178, variants: ['Palette'], description: '12-shade professional eyeshadow palette.', images: [{ url: productImageMap['demo-mk-03'], alt: 'Smoky Eye Palette', isPrimary: true }], inStock: true, benefits: ['12 shades', 'High pigment'] },
  { _id: 'demo-mk-04', slug: 'rosy-cheek-tint', name: 'Rosy Cheek Tint', category: 'makeup', price: 1899, originalPrice: 2299, rating: 4.5, reviewCount: 67, variants: ['Rose','Peach','Berry'], description: 'Cream blush for natural glow.', images: [{ url: productImageMap['demo-mk-04'], alt: 'Rosy Cheek Tint', isPrimary: true }], inStock: true, benefits: ['Natural glow', 'Buildable'] },
  { _id: 'demo-mk-05', slug: 'lengthening-mascara', name: 'Lengthening Mascara', category: 'makeup', price: 1699, originalPrice: 1999, rating: 4.4, reviewCount: 145, variants: ['Black','Brown'], description: 'Volumizing lengthening mascara.', images: [{ url: productImageMap['demo-mk-05'], alt: 'Lengthening Mascara', isPrimary: true }], inStock: true, benefits: ['Volume + Length', 'Smudge-proof'] },
  { _id: 'demo-mk-06', slug: 'moonlight-highlighter', name: 'Moonlight Highlighter', category: 'makeup', price: 2299, originalPrice: 2799, rating: 4.6, reviewCount: 112, variants: ['Champagne','Rose Gold','Bronze'], description: 'Luminous celestial highlighter.', images: [{ url: productImageMap['demo-mk-06'], alt: 'Moonlight Highlighter', isPrimary: true }], inStock: true, benefits: ['Intense glow', 'Blendable'] },
  { _id: 'demo-mk-07', slug: 'silk-primer', name: 'Silk Priming Mist', category: 'makeup', price: 1599, originalPrice: 1999, badge: 'New', rating: 4.3, reviewCount: 56, variants: ['50ml','100ml'], description: 'Hydrating makeup primer spray.', images: [{ url: productImageMap['demo-mk-07'], alt: 'Silk Primer', isPrimary: true }], inStock: true, benefits: ['Smooth base', 'Long-lasting'] },
  { _id: 'demo-mk-08', slug: 'full-coverage-concealer', name: 'Full Coverage Concealer', category: 'makeup', price: 1999, originalPrice: 2399, rating: 4.5, reviewCount: 89, variants: ['Light','Medium','Warm'], description: 'Full coverage concealer with hyaluronic acid.', images: [{ url: productImageMap['demo-mk-08'], alt: 'Full Coverage Concealer', isPrimary: true }], inStock: true, benefits: ['Full coverage', 'Hydrating'] },
  { _id: 'demo-mk-09', slug: 'lip-gloss-shine', name: 'Lip Gloss Shine', category: 'makeup', price: 1299, originalPrice: 1599, badge: 'Sale', rating: 4.2, reviewCount: 63, variants: ['Clear','Rose','Gold'], description: 'High shine lip gloss with vitamin E.', images: [{ url: productImageMap['demo-mk-09'], alt: 'Lip Gloss Shine', isPrimary: true }], inStock: true, benefits: ['High shine', 'Nourishing'] },
  { _id: 'demo-mk-10', slug: 'precision-brow-pencil', name: 'Precision Brow Pencil', category: 'makeup', price: 999, originalPrice: 1199, rating: 4.4, reviewCount: 78, variants: ['Blonde','Brown','Dark'], description: 'Ultra-fine brow pencil for precise shaping.', images: [{ url: productImageMap['demo-mk-10'], alt: 'Brow Pencil', isPrimary: true }], inStock: true, benefits: ['Precise', 'Natural look'] },
  { _id: 'demo-mk-11', slug: 'setting-spray', name: 'Makeup Setting Spray', category: 'makeup', price: 1499, originalPrice: 1799, rating: 4.6, reviewCount: 92, variants: ['100ml','200ml'], description: 'Long-lasting makeup setting spray.', images: [{ url: productImageMap['demo-mk-11'], alt: 'Setting Spray', isPrimary: true }], inStock: true, benefits: ['All-day wear', 'Hydrating'] },
  { _id: 'demo-mk-12', slug: 'contour-stick', name: 'Contour Stick', category: 'makeup', price: 2199, originalPrice: 2599, badge: 'Best Seller', rating: 4.7, reviewCount: 103, variants: ['Light','Medium','Dark'], description: 'Cream contour stick for sculpting.', images: [{ url: productImageMap['demo-mk-12'], alt: 'Contour Stick', isPrimary: true }], inStock: true, benefits: ['Sculpts', 'Blendable'] },
  // ===== HAIRCARE (10 products) =====
  { _id: 'demo-hc-01', slug: 'silk-hair-elixir', name: 'Silk Hair Elixir', category: 'haircare', price: 1999, originalPrice: 2499, rating: 4.7, reviewCount: 56, variants: ['100ml','200ml'], description: 'Silky smooth hair with argan and keratin.', images: [{ url: productImageMap['demo-hc-01'], alt: 'Silk Hair Elixir', isPrimary: true }], inStock: true, benefits: ['Silky smooth', 'Reduces frizz'] },
  { _id: 'demo-hc-02', slug: 'volumizing-shampoo', name: 'Volumizing Shampoo', category: 'haircare', price: 1499, originalPrice: 1799, rating: 4.5, reviewCount: 78, variants: ['200ml','400ml'], description: 'Volume-boosting gentle shampoo.', images: [{ url: productImageMap['demo-hc-02'], alt: 'Volumizing Shampoo', isPrimary: true }], inStock: true, benefits: ['Adds volume', 'Gentle cleanse'] },
  { _id: 'demo-hc-03', slug: 'hydrating-conditioner', name: 'Hydrating Conditioner', category: 'haircare', price: 1599, originalPrice: 1899, rating: 4.4, reviewCount: 52, variants: ['200ml','400ml'], description: 'Moisturizing detangling conditioner.', images: [{ url: productImageMap['demo-hc-03'], alt: 'Hydrating Conditioner', isPrimary: true }], inStock: true, benefits: ['Deep hydration', 'Detangles'] },
  { _id: 'demo-hc-04', slug: 'repair-hair-serum', name: 'Repair Hair Serum', category: 'haircare', price: 2199, originalPrice: 2599, badge: 'Best Seller', rating: 4.6, reviewCount: 89, variants: ['100ml','150ml'], description: 'Repair and protect hair serum.', images: [{ url: productImageMap['demo-hc-04'], alt: 'Repair Hair Serum', isPrimary: true }], inStock: true, benefits: ['Repairs damage', 'Heat protection'] },
  { _id: 'demo-hc-05', slug: 'deep-nourish-hair-mask', name: 'Deep Nourish Hair Mask', category: 'haircare', price: 2499, originalPrice: 2899, rating: 4.7, reviewCount: 103, variants: ['200ml'], description: 'Weekly deep conditioning mask.', images: [{ url: productImageMap['demo-hc-05'], alt: 'Deep Nourish Hair Mask', isPrimary: true }], inStock: true, benefits: ['Deep conditioning', 'Repairs damage'] },
  { _id: 'demo-hc-06', slug: 'shine-hair-spray', name: 'Shine Hair Spray', category: 'haircare', price: 1299, originalPrice: 1499, rating: 4.3, reviewCount: 41, variants: ['150ml'], description: 'Luminous finishing hair spray.', images: [{ url: productImageMap['demo-hc-06'], alt: 'Shine Hair Spray', isPrimary: true }], inStock: true, benefits: ['High shine', 'Light hold'] },
  { _id: 'demo-hc-07', slug: 'leave-in-conditioner', name: 'Leave-In Conditioner', category: 'haircare', price: 1399, originalPrice: 1699, badge: 'New', rating: 4.5, reviewCount: 38, variants: ['200ml'], description: 'Weightless leave-in conditioner with argan oil.', images: [{ url: productImageMap['demo-hc-07'], alt: 'Leave In Conditioner', isPrimary: true }], inStock: true, benefits: ['Detangles', 'Hydrates'] },
  { _id: 'demo-hc-08', slug: 'dry-shampoo', name: 'Dry Shampoo', category: 'haircare', price: 999, originalPrice: 1199, rating: 4.3, reviewCount: 67, variants: ['150ml','250ml'], description: 'Instant refresh dry shampoo.', images: [{ url: productImageMap['demo-hc-08'], alt: 'Dry Shampoo', isPrimary: true }], inStock: true, benefits: ['Instant refresh', 'Volume'] },
  { _id: 'demo-hc-09', slug: 'smoothing-hair-cream', name: 'Smoothing Hair Cream', category: 'haircare', price: 1799, originalPrice: 2199, rating: 4.4, reviewCount: 45, variants: ['150ml'], description: 'Anti-frizz smoothing hair cream.', images: [{ url: productImageMap['demo-hc-09'], alt: 'Hair Cream', isPrimary: true }], inStock: true, benefits: ['Smooths', 'Anti-frizz'] },
  { _id: 'demo-hc-10', slug: 'scalp-treatment', name: 'Scalp Treatment Serum', category: 'haircare', price: 2499, originalPrice: 2999, badge: 'New', rating: 4.6, reviewCount: 34, variants: ['50ml','100ml'], description: 'Nourishing scalp treatment for healthy hair.', images: [{ url: productImageMap['demo-hc-10'], alt: 'Scalp Treatment', isPrimary: true }], inStock: true, benefits: ['Healthy scalp', 'Strengthens'] },
  // ===== FRAGRANCE (10 products) =====
  { _id: 'demo-fr-01', slug: 'rose-petal-mist', name: 'Rose Petal Mist', category: 'fragrance', price: 1299, originalPrice: 1499, rating: 4.5, reviewCount: 34, variants: ['100ml','150ml'], description: 'Instant hydration with rose water.', images: [{ url: productImageMap['demo-fr-01'], alt: 'Rose Petal Mist', isPrimary: true }], inStock: true, benefits: ['Refreshing', 'Sets makeup'] },
  { _id: 'demo-fr-02', slug: 'midnight-oud-perfume', name: 'Midnight Oud Perfume', category: 'fragrance', price: 5499, originalPrice: 6499, badge: 'Exclusive', rating: 4.8, reviewCount: 167, variants: ['50ml','100ml'], description: 'Elegant oud fragrance for evening.', images: [{ url: productImageMap['demo-fr-02'], alt: 'Midnight Oud Perfume', isPrimary: true }], inStock: true, benefits: ['Long-lasting', 'Luxury scent'] },
  { _id: 'demo-fr-03', slug: 'vanilla-dream-spray', name: 'Vanilla Dream Spray', category: 'fragrance', price: 1599, originalPrice: 1899, rating: 4.4, reviewCount: 82, variants: ['100ml','200ml'], description: 'Sweet vanilla body mist.', images: [{ url: productImageMap['demo-fr-03'], alt: 'Vanilla Dream Spray', isPrimary: true }], inStock: true, benefits: ['Sweet scent', 'Long-lasting'] },
  { _id: 'demo-fr-04', slug: 'fresh-citrus-deodorant', name: 'Fresh Citrus Deodorant', category: 'fragrance', price: 999, originalPrice: 1199, rating: 4.3, reviewCount: 45, variants: ['50ml'], description: 'Refreshing citrus deodorant.', images: [{ url: productImageMap['demo-fr-04'], alt: 'Fresh Citrus Deodorant', isPrimary: true }], inStock: true, benefits: ['24hr protection', 'Refreshing'] },
  { _id: 'demo-fr-05', slug: 'rose-gold-candle', name: 'Rose Gold Candle', category: 'fragrance', price: 1899, originalPrice: 2299, rating: 4.6, reviewCount: 73, variants: ['200g'], description: 'Luxurious rose gold candle.', images: [{ url: productImageMap['demo-fr-05'], alt: 'Rose Gold Candle', isPrimary: true }], inStock: true, benefits: ['40hr burn time', 'Luxury scent'] },
  { _id: 'demo-fr-06', slug: 'luxury-gift-set', name: 'Luxury Gift Set', category: 'fragrance', price: 4999, originalPrice: 5999, badge: 'Sale', rating: 4.7, reviewCount: 91, variants: ['Gift Set'], description: 'Premium fragrance gift collection.', images: [{ url: productImageMap['demo-fr-06'], alt: 'Luxury Gift Set', isPrimary: true }], inStock: true, benefits: ['5pc set', 'Perfect gift'] },
  { _id: 'demo-fr-07', slug: 'rose-intense-edp', name: 'Rose Intense EDP', category: 'fragrance', price: 3999, originalPrice: 4999, badge: 'Best Seller', rating: 4.7, reviewCount: 134, variants: ['50ml','100ml'], description: 'Intense rose perfume with musk notes.', images: [{ url: productImageMap['demo-fr-07'], alt: 'Rose Intense EDP', isPrimary: true }], inStock: true, benefits: ['Intense scent', 'Long-lasting'] },
  { _id: 'demo-fr-08', slug: 'premium-oud-oil', name: 'Premium Oud Oil Roll-On', category: 'fragrance', price: 2999, originalPrice: 3599, rating: 4.5, reviewCount: 67, variants: ['10ml','20ml'], description: 'Concentrated oud perfume oil roll-on.', images: [{ url: productImageMap['demo-fr-08'], alt: 'Oud Oil', isPrimary: true }], inStock: true, benefits: ['Concentrated', 'Travel-friendly'] },
  { _id: 'demo-fr-09', slug: 'lavender-mist', name: 'Lavender Relax Mist', category: 'fragrance', price: 1199, originalPrice: 1399, rating: 4.4, reviewCount: 45, variants: ['100ml','200ml'], description: 'Calming lavender body and room mist.', images: [{ url: productImageMap['demo-fr-09'], alt: 'Lavender Mist', isPrimary: true }], inStock: true, benefits: ['Calming', 'Aromatherapy'] },
  { _id: 'demo-fr-10', slug: 'jasmine-spray', name: 'Jasmine Bloom Spray', category: 'fragrance', price: 1799, originalPrice: 2199, badge: 'New', rating: 4.6, reviewCount: 56, variants: ['100ml'], description: 'Fresh jasmine flower body spray.', images: [{ url: productImageMap['demo-fr-10'], alt: 'Jasmine Spray', isPrimary: true }], inStock: true, benefits: ['Floral scent', 'All-day fresh'] },
  // ===== BODY CARE (10 products) =====
  { _id: 'demo-bc-01', slug: 'luxe-body-lotion', name: 'Luxe Body Lotion', category: 'body-care', price: 1799, originalPrice: 2199, badge: 'Sale', rating: 4.4, reviewCount: 67, variants: ['200ml','400ml'], description: 'Soft, smooth skin with shea butter.', images: [{ url: productImageMap['demo-bc-01'], alt: 'Luxe Body Lotion', isPrimary: true }], inStock: true, benefits: ['Deep hydration', 'Non-greasy'] },
  { _id: 'demo-bc-02', slug: 'rose-sugar-scrub', name: 'Rose Sugar Scrub', category: 'body-care', price: 1499, originalPrice: 1799, rating: 4.5, reviewCount: 54, variants: ['200ml'], description: 'Gentle exfoliating sugar scrub.', images: [{ url: productImageMap['demo-bc-02'], alt: 'Rose Sugar Scrub', isPrimary: true }], inStock: true, benefits: ['Exfoliates', 'Hydrates'] },
  { _id: 'demo-bc-03', slug: 'shea-body-butter', name: 'Shea Body Butter', category: 'body-care', price: 2199, originalPrice: 2599, rating: 4.6, reviewCount: 78, variants: ['200ml'], description: 'Intensive moisturizing body butter.', images: [{ url: productImageMap['demo-bc-03'], alt: 'Shea Body Butter', isPrimary: true }], inStock: true, benefits: ['Intense moisture', 'Repairs dry skin'] },
  { _id: 'demo-bc-04', slug: 'relaxing-body-oil', name: 'Relaxing Body Oil', category: 'body-care', price: 1999, originalPrice: 2299, rating: 4.5, reviewCount: 62, variants: ['100ml','200ml'], description: 'Relaxing lavender body oil.', images: [{ url: productImageMap['demo-bc-04'], alt: 'Relaxing Body Oil', isPrimary: true }], inStock: true, benefits: ['Relaxing scent', 'Nourishes'] },
  { _id: 'demo-bc-05', slug: 'artisan-soap-bar', name: 'Artisan Soap Bar', category: 'body-care', price: 799, originalPrice: 999, rating: 4.3, reviewCount: 41, variants: ['Single','Pack of 3'], description: 'Natural handcrafted soap bar.', images: [{ url: productImageMap['demo-bc-05'], alt: 'Artisan Soap Bar', isPrimary: true }], inStock: true, benefits: ['Natural', 'Gentle cleanse'] },
  { _id: 'demo-bc-06', slug: 'hand-cream', name: 'Hand Cream', category: 'body-care', price: 899, originalPrice: 1099, rating: 4.4, reviewCount: 38, variants: ['50ml','100ml'], description: 'Moisturizing hand cream.', images: [{ url: productImageMap['demo-bc-06'], alt: 'Hand Cream', isPrimary: true }], inStock: true, benefits: ['Deep hydration', 'Fast absorbing'] },
  { _id: 'demo-bc-07', slug: 'luxe-shower-gel', name: 'Luxe Shower Gel', category: 'body-care', price: 1299, originalPrice: 1599, badge: 'Sale', rating: 4.4, reviewCount: 56, variants: ['200ml','400ml'], description: 'Luxurious moisturizing shower gel.', images: [{ url: productImageMap['demo-bc-07'], alt: 'Luxe Shower Gel', isPrimary: true }], inStock: true, benefits: ['Moisturizes', 'Aromatherapy'] },
  { _id: 'demo-bc-08', slug: 'rose-bath-bomb', name: 'Rose Bath Bomb Set', category: 'body-care', price: 999, originalPrice: 1299, rating: 4.5, reviewCount: 73, variants: ['Set of 3','Set of 6'], description: 'Fizzing rose scented bath bombs.', images: [{ url: productImageMap['demo-bc-08'], alt: 'Rose Bath Bomb', isPrimary: true }], inStock: true, benefits: ['Relaxing', 'Scented'] },
  { _id: 'demo-bc-09', slug: 'cooling-foot-cream', name: 'Cooling Foot Cream', category: 'body-care', price: 899, originalPrice: 1099, rating: 4.3, reviewCount: 34, variants: ['100ml'], description: 'Refreshing foot cream with peppermint.', images: [{ url: productImageMap['demo-bc-09'], alt: 'Foot Cream', isPrimary: true }], inStock: true, benefits: ['Cooling', 'Refreshes'] },
  { _id: 'demo-bc-10', slug: 'massage-oil', name: 'Relaxing Massage Oil', category: 'body-care', price: 1699, originalPrice: 1999, rating: 4.5, reviewCount: 47, variants: ['200ml'], description: 'Warm massage oil for relaxation.', images: [{ url: productImageMap['demo-bc-10'], alt: 'Massage Oil', isPrimary: true }], inStock: true, benefits: ['Relaxing', 'Nourishes'] },
];




const LOCAL_IMAGE_POOLS = {
  'demo-sk': [
    'skincare-serum.svg',
    'skincare-cream.svg',
    'skincare-mist.svg',
    'skincare-cleanser.svg',
    'skincare-moisturizer.svg',
    'skincare-sunscreen.svg',
    'skincare-vitamin-c.svg',
    'skincare-toner.svg',
    'skincare-eye-cream.svg',
    'skincare-face-wash.svg',
    'skincare-night-cream.svg',
    'skincare-mask.svg',
  ],

  'demo-mk': [
    'makeup-lipstick.svg',
    'makeup-foundation.svg',
    'makeup-eyeshadow.svg',
    'makeup-blush.svg',
    'makeup-mascara.svg',
    'makeup-highlighter.svg',
    'makeup-primer.svg',
    'makeup-concealer.svg',
    'makeup-lip-gloss.svg',
    'makeup-brow.svg',
    'makeup-setting-spray.svg',
    'makeup-contour.svg',
  ],

  'demo-hc': [
    'haircare-oil.svg',
    'haircare-shampoo.svg',
    'haircare-conditioner.svg',
    'haircare-serum.svg',
    'haircare-mask.svg',
    'haircare-spray.svg',
    'haircare-leave-in.svg',
    'haircare-dry-shampoo.svg',
    'haircare-hair-cream.svg',
    'haircare-scalp-treatment.svg',
  ],

  'demo-fr': [
    'fragrance-mist.svg',
    'fragrance-perfume.svg',
    'fragrance-body-spray.svg',
    'fragrance-deodorant.svg',
    'fragrance-candle.svg',
    'fragrance-gift-set.svg',
    'fragrance-rose-perfume.svg',
    'fragrance-oud-oil.svg',
    'fragrance-lavender.svg',
    'fragrance-jasmine.svg',
  ],

  'demo-bc': [
    'body-care-lotion.svg',
    'body-care-scrub.svg',
    'body-care-butter.svg',
    'body-care-oil.svg',
    'body-care-soap.svg',
    'body-care-cream.svg',
    'body-care-shower-gel.svg',
    'body-care-bath-bomb.svg',
    'body-care-foot-cream.svg',
    'body-care-massage-oil.svg',
  ],
};

const getDemoImage = (id) => {
  const match = id?.match(/^(demo-(?:sk|mk|hc|fr|bc))-(\d+)$/);

  if (!match) return '/images/products/skincare-serum.svg';

  const [, prefix, number] = match;
  const images = LOCAL_IMAGE_POOLS[prefix];
  const index = Number(number) - 1;

  return `/images/products/${images?.[index] || images?.[0] || 'skincare-serum.svg'}`;
};

// Fix all demo product image URLs
demoProducts.forEach((product) => {
  const image = getDemoImage(product._id);

  product.images = [
    {
      url: image,
      alt: product.name,
      isPrimary: true,
    },
  ];

  product.image = image;
});








export async function GET(request) {
  try {
    const { searchParams } = new URL(request.url);
    const category = searchParams.get('category');
    const search = searchParams.get('search');
    const filter = searchParams.get('filter');

    let products = [];
    let usedFallback = false;
    try {
      await connectDB();
      let query = {};
      
      if (filter === 'bestsellers') {
        query = { badge: 'Best Seller' };
      } else if (filter === 'new') {
        query = { badge: 'New' };
      } else if (filter === 'sale') {
        query = { badge: 'Sale' };
      }
      
      products = await Product.find(query).sort({ createdAt: -1 }).lean();
    } catch (e) {
      products = [...demoProducts];
      usedFallback = true;
    }

    if (!usedFallback && products.length === 0) {
      products = [...demoProducts];
      usedFallback = true;
    }
    
    // Merge demo product images if database products don't have local images or have old SVG paths
    if (!usedFallback) {
      const demoMap = new Map(demoProducts.map(p => [p.name.toLowerCase(), p]));
      products = products.map(p => {
        const demo = demoMap.get((p.name || '').toLowerCase());
        if (demo) {
          const hasOldSvgImages = p.images && p.images.some(img => img.url && img.url.includes('.svg') && !img.url.startsWith('/images/products/'));
          const hasExternalImages = p.images && p.images.some(img => img.url && img.url.startsWith('http'));
          if (!p.images || p.images.length === 0 || hasOldSvgImages || hasExternalImages) {
            return { ...p, images: demo.images, image: demo.images[0]?.url, slug: demo.slug };
          }
        }
        return p;
      });
    }

    // Local image pool for any product without images — ordered to match category grouping
    const beautyImagePool = [
      '/images/products/skincare-serum.svg',
      '/images/products/skincare-cream.svg',
      '/images/products/skincare-mist.svg',
      '/images/products/skincare-cleanser.svg',
      '/images/products/skincare-moisturizer.svg',
      '/images/products/skincare-sunscreen.svg',
      '/images/products/skincare-vitamin-c.svg',
      '/images/products/skincare-toner.svg',
      '/images/products/skincare-eye-cream.svg',
      '/images/products/skincare-face-wash.svg',
      '/images/products/skincare-night-cream.svg',
      '/images/products/skincare-mask.svg',
      '/images/products/makeup-lipstick.svg',
      '/images/products/makeup-foundation.svg',
      '/images/products/makeup-eyeshadow.svg',
      '/images/products/makeup-blush.svg',
      '/images/products/makeup-mascara.svg',
      '/images/products/makeup-highlighter.svg',
      '/images/products/makeup-primer.svg',
      '/images/products/makeup-concealer.svg',
      '/images/products/makeup-lip-gloss.svg',
      '/images/products/makeup-brow.svg',
      '/images/products/makeup-setting-spray.svg',
      '/images/products/makeup-contour.svg',
      '/images/products/haircare-oil.svg',
      '/images/products/haircare-shampoo.svg',
      '/images/products/haircare-conditioner.svg',
      '/images/products/haircare-serum.svg',
      '/images/products/haircare-mask.svg',
      '/images/products/haircare-spray.svg',
      '/images/products/haircare-leave-in.svg',
      '/images/products/haircare-dry-shampoo.svg',
      '/images/products/haircare-hair-cream.svg',
      '/images/products/haircare-scalp-treatment.svg',
      '/images/products/fragrance-mist.svg',
      '/images/products/fragrance-perfume.svg',
      '/images/products/fragrance-body-spray.svg',
      '/images/products/fragrance-deodorant.svg',
      '/images/products/fragrance-candle.svg',
      '/images/products/fragrance-gift-set.svg',
      '/images/products/fragrance-rose-perfume.svg',
      '/images/products/fragrance-oud-oil.svg',
      '/images/products/fragrance-lavender.svg',
      '/images/products/fragrance-jasmine.svg',
      '/images/products/body-care-lotion.svg',
      '/images/products/body-care-scrub.svg',
      '/images/products/body-care-butter.svg',
      '/images/products/body-care-oil.svg',
      '/images/products/body-care-soap.svg',
      '/images/products/body-care-cream.svg',
      '/images/products/body-care-shower-gel.svg',
      '/images/products/body-care-bath-bomb.svg',
      '/images/products/body-care-foot-cream.svg',
      '/images/products/body-care-massage-oil.svg'
    ];

    // Apply the same image to ALL products as requested
    // const ALL_PRODUCT_IMAGE = '/images/products/makeup-eyeshadow.svg';

    // products = products.map((p) => {
    //   const mergedImages = [
    //     { url: ALL_PRODUCT_IMAGE, alt: p.name, isPrimary: true }
    //   ];
      
    //   return { ...p, images: mergedImages, image: ALL_PRODUCT_IMAGE };
    // });

products = products.map((p) => {
  const demo = demoProducts.find(
    (d) =>
      d._id === p._id ||
      d.name?.toLowerCase() === p.name?.toLowerCase()
  );

  if (demo) {
    return {
      ...p,
      images: demo.images,
      image: demo.image,
      slug: demo.slug,
    };
  }

  const existingImages = Array.isArray(p.images)
    ? p.images.filter(
        (img) => img?.url && img.url.trim() !== ''
      )
    : [];

  const primaryUrl =
    existingImages[0]?.url ||
    '/images/products/skincare-serum.svg';

  return {
    ...p,
    images: [
      {
        url: primaryUrl,
        alt: p.name,
        isPrimary: true,
      },
    ],
    image: primaryUrl,
  };
});

    // Filter by category
    if (category && category !== 'all') {
      const targetCat = category.toLowerCase();
      products = products.filter((p) => (p.category || '').toLowerCase() === targetCat);
      console.log('Filtered by category:', category, 'count:', products.length);
    }
    // Search
    if (search) {
      const q = search.toLowerCase();
      products = products.filter((p) => ((p.name || '').toLowerCase().includes(q) || (p.description || '').toLowerCase().includes(q)));
    }

    // Filter by badge
    if (usedFallback && filter) {
      const badgeMap = { 'bestsellers': 'Best Seller', 'new': 'New', 'sale': 'Sale' };
      const targetBadge = badgeMap[filter.toLowerCase()] || filter;
      products = products.filter((p) => p.badge === targetBadge);
    }

    return Response.json({ success: true, products, fallback: usedFallback });
  } catch (error) {
    return Response.json({ success: true, products: [...demoProducts], fallback: true });
  }
}

export async function POST(request) {
  try {
    const body = await request.json();
    const { name, price, description, category, images, variants, stock, rating, reviewCount, badge } = body;

    if (!name || !price) {
      return Response.json({ success: false, message: 'Name and price are required' }, { status: 400 });
    }

    try {
      await connectDB();
      const product = await Product.create({
        name,
        price: parseFloat(price),
        description: description || '',
        category: category || 'uncategorized',
        images: images || [],
        variants: variants || [],
        stock: typeof stock === 'number' ? stock : 999,
        rating: typeof rating === 'number' ? rating : 4.5,
        reviewCount: typeof reviewCount === 'number' ? reviewCount : 0,
        badge,
        inStock: !(typeof stock === 'number' && stock === 0),
      });
      return Response.json({ success: true, product }, { status: 201 });
    } catch (e) {
      const created = { _id: 'local-' + Math.random().toString(36).slice(2), name, price: parseFloat(price), description: description || '', category: category || 'uncategorized', images: images || [], variants: variants || [], stock: typeof stock === 'number' ? stock : 999, rating: typeof rating === 'number' ? rating : 4.5, reviewCount: typeof reviewCount === 'number' ? reviewCount : 0, badge, inStock: !(typeof stock === 'number' && stock === 0) };
      return Response.json({ success: true, product: created, fallback: true }, { status: 201 });
    }
  } catch (error) {
    return Response.json({ success: false, error: error.message }, { status: 500 });
  }
}