/**
 * Beauty_Pro - Seed Database Route
 */

import { connectDB } from '@/lib/db';
import Product from '@/models/Product';
import Category from '@/models/Category';

export const dynamic = 'force-dynamic';

export async function POST(request) {
  try {
    await connectDB();

    // Create categories first
    const categories = [
      { name: 'Skincare', slug: 'skincare', description: 'Luxurious skincare products for radiant skin', image: '/images/products/skincare-serum.svg', productCount: 0 },
      { name: 'Makeup', slug: 'makeup', description: 'Premium makeup for every occasion', image: '/images/products/makeup-lipstick.svg', productCount: 0 },
      { name: 'Haircare', slug: 'haircare', description: 'Nourishing haircare essentials', image: '/images/products/haircare-oil.svg', productCount: 0 },
      { name: 'Fragrance', slug: 'fragrance', description: 'Exclusive fragrances and perfumes', image: '/images/products/fragrance-mist.svg', productCount: 0 },
      { name: 'Body Care', slug: 'body-care', description: 'Indulgent body care products', image: '/images/products/body-care-lotion.svg', productCount: 0 },
    ];

    for (const cat of categories) {
      await Category.findOneAndUpdate({ slug: cat.slug }, cat, { upsert: true, new: true });
    }

    const products = [
      // SKINCARE (12 products)
      { name: 'Rose Gold Radiance Serum', slug: 'rose-gold-radiance-serum', category: 'skincare', description: '24k gold serum for radiant skin', price: 3499, originalPrice: 4999, badge: 'Best Seller', rating: 4.8, reviewCount: 124, stock: 50, images: [{ url: '/images/products/skincare-serum.svg', alt: 'Rose Gold Radiance Serum', isPrimary: true }], benefits: ['Deep hydration', 'Anti-aging', 'Brightening'], ingredients: '24k Gold, Rose Water, Hyaluronic Acid', howToUse: 'Apply 2-3 drops daily' },
      { name: 'Diamond Radiance Cream', slug: 'diamond-radiance-cream', category: 'skincare', description: 'Diamond-infused luxury moisturizer', price: 4999, originalPrice: 5999, badge: 'Exclusive', rating: 4.9, reviewCount: 210, stock: 30, images: [{ url: '/images/products/skincare-cream.svg', alt: 'Diamond Radiance Cream', isPrimary: true }], benefits: ['Intense hydration', 'Anti-aging'], ingredients: 'Diamond Powder, Shea Butter, Peptides', howToUse: 'Apply morning and evening' },
      { name: 'Midnight Recovery Oil', slug: 'midnight-recovery-oil', category: 'skincare', description: 'Overnight rejuvenation oil', price: 3799, originalPrice: 4299, badge: 'Best Seller', rating: 4.7, reviewCount: 145, stock: 40, images: [{ url: '/images/products/skincare-mist.svg', alt: 'Midnight Recovery Oil', isPrimary: true }], benefits: ['Overnight repair', 'Nourishes skin'], ingredients: 'Rosehip Oil, Retinol, Vitamin E', howToUse: 'Apply at night before bed' },
      { name: 'Gentle Foaming Cleanser', slug: 'gentle-foaming-cleanser', category: 'skincare', description: 'Gentle daily cleanser for all skin types', price: 1599, originalPrice: 1999, rating: 4.6, reviewCount: 89, stock: 100, images: [{ url: '/images/products/skincare-cleanser.svg', alt: 'Gentle Foaming Cleanser', isPrimary: true }], benefits: ['Deep cleanses', 'Gentle formula'], ingredients: 'Glycolic Acid, Aloe Vera, Glycerin', howToUse: 'Use morning and evening' },
      { name: 'Hydra Boost Moisturizer', slug: 'hydra-boost-moisturizer', category: 'skincare', description: '24-hour hydration moisturizer', price: 2499, originalPrice: 2999, rating: 4.7, reviewCount: 156, stock: 80, images: [{ url: '/images/products/skincare-moisturizer.svg', alt: 'Hydra Boost Moisturizer', isPrimary: true }], benefits: ['24hr hydration', 'Non-greasy'], ingredients: 'Hyaluronic Acid, Ceramides, Vitamin B5', howToUse: 'Apply to face and neck' },
      { name: 'Daily Defense SPF 50', slug: 'daily-defense-spf-50', category: 'skincare', description: 'Broad spectrum SPF 50 protection', price: 1899, originalPrice: 2199, badge: 'New', rating: 4.8, reviewCount: 98, stock: 60, images: [{ url: '/images/products/skincare-sunscreen.svg', alt: 'Daily Defense SPF 50', isPrimary: true }], benefits: ['SPF 50', 'Lightweight'], ingredients: 'Zinc Oxide, Niacinamide, Vitamin E', howToUse: 'Apply 15 mins before sun exposure' },
      { name: 'Vitamin C Brightening Serum', slug: 'vitamin-c-brightening-serum', category: 'skincare', description: 'Brightening vitamin C serum with hyaluronic acid', price: 2899, originalPrice: 3499, rating: 4.6, reviewCount: 67, stock: 45, images: [{ url: '/images/products/skincare-vitamin-c.svg', alt: 'Vitamin C Brightening Serum', isPrimary: true }], benefits: ['Brightens', 'Even tone'], ingredients: 'Vitamin C, Hyaluronic Acid, Vitamin E', howToUse: 'Apply after cleansing' },
      { name: 'Rose Petal Toner Mist', slug: 'rose-petal-toner', category: 'skincare', description: 'Hydrating rose water toner', price: 1299, originalPrice: 1599, rating: 4.4, reviewCount: 56, stock: 70, images: [{ url: '/images/products/skincare-toner.svg', alt: 'Rose Petal Toner', isPrimary: true }], benefits: ['Hydrates', 'Refreshes'], ingredients: 'Rose Water, Glycerin, Aloe Vera', howToUse: 'Spray after cleansing' },
      { name: 'Golden Eye Cream', slug: 'golden-eye-cream', category: 'skincare', description: 'Luxury eye cream with gold particles', price: 3299, originalPrice: 3999, rating: 4.5, reviewCount: 78, stock: 35, images: [{ url: '/images/products/skincare-eye-cream.svg', alt: 'Golden Eye Cream', isPrimary: true }], benefits: ['Reduces puffiness', 'Anti-aging'], ingredients: 'Gold Particles, Caffeine, Peptides', howToUse: 'Gently pat under eyes' },
      { name: 'Gentle Face Wash', slug: 'gentle-face-wash', category: 'skincare', description: 'Mild daily face wash for all skin types', price: 999, originalPrice: 1299, badge: 'Sale', rating: 4.3, reviewCount: 112, stock: 90, images: [{ url: '/images/products/skincare-face-wash.svg', alt: 'Gentle Face Wash', isPrimary: true }], benefits: ['Gentle cleanse', 'pH balanced'], ingredients: 'Aloe Vera, Green Tea, Glycerin', howToUse: 'Massage onto wet face and rinse' },
      { name: 'Luxe Night Cream', slug: 'luxe-night-cream', category: 'skincare', description: 'Rich overnight night cream with retinol', price: 4499, originalPrice: 5499, badge: 'Exclusive', rating: 4.8, reviewCount: 89, stock: 25, images: [{ url: '/images/products/skincare-night-cream.svg', alt: 'Luxe Night Cream', isPrimary: true }], benefits: ['Repairs overnight', 'Anti-aging'], ingredients: 'Retinol, Peptides, Shea Butter', howToUse: 'Apply before bed' },
      { name: 'Glow Sheet Mask Pack', slug: 'glow-sheet-mask', category: 'skincare', description: 'Hydrating sheet mask for instant glow', price: 699, originalPrice: 899, rating: 4.4, reviewCount: 145, stock: 120, images: [{ url: '/images/products/skincare-mask.svg', alt: 'Glow Sheet Mask', isPrimary: true }], benefits: ['Instant glow', 'Hydrates'], ingredients: 'Hyaluronic Acid, Vitamin C, Niacinamide', howToUse: 'Leave on for 15-20 mins' },
      // MAKEUP (12 products)
      { name: 'Velvet Matte Lipstick', slug: 'velvet-matte-lipstick', category: 'makeup', description: 'Long-wear matte lipstick', price: 2499, originalPrice: 2999, badge: 'New', rating: 4.6, reviewCount: 89, stock: 75, images: [{ url: '/images/products/makeup-lipstick.svg', alt: 'Velvet Matte Lipstick', isPrimary: true }], benefits: ['16hr wear', 'Intense color'], ingredients: 'Vitamin E, Jojoba Oil, Pigments', howToUse: 'Apply directly to lips' },
      { name: 'Glow Foundation SPF 25', slug: 'glow-foundation', category: 'makeup', description: 'Dewy foundation with SPF 25', price: 2799, originalPrice: 3199, rating: 4.3, reviewCount: 92, stock: 65, images: [{ url: '/images/products/makeup-foundation.svg', alt: 'Glow Foundation', isPrimary: true }], benefits: ['Dewy finish', 'SPF 25'], ingredients: 'Hyaluronic Acid, SPF filters', howToUse: 'Apply with brush or sponge' },
      { name: 'Smoky Eye Palette', slug: 'smoky-eye-palette', category: 'makeup', description: '12-shade professional eyeshadow palette', price: 3999, originalPrice: 4499, badge: 'Best Seller', rating: 4.8, reviewCount: 178, stock: 40, images: [{ url: '/images/products/makeup-eyeshadow.svg', alt: 'Smoky Eye Palette', isPrimary: true }], benefits: ['12 shades', 'High pigment'], ingredients: 'Mica, Silica, Vitamin E', howToUse: 'Apply with brush for desired look' },
      { name: 'Rosy Cheek Tint', slug: 'rosy-cheek-tint', category: 'makeup', description: 'Cream blush for natural glow', price: 1899, originalPrice: 2299, rating: 4.5, reviewCount: 67, stock: 55, images: [{ url: '/images/products/makeup-blush.svg', alt: 'Rosy Cheek Tint', isPrimary: true }], benefits: ['Natural glow', 'Buildable'], ingredients: 'Shea Butter, Vitamin E, Pigments', howToUse: 'Dab on cheeks and blend' },
      { name: 'Lengthening Mascara', slug: 'lengthening-mascara', category: 'makeup', description: 'Volumizing lengthening mascara', price: 1699, originalPrice: 1999, rating: 4.4, reviewCount: 145, stock: 85, images: [{ url: '/images/products/makeup-mascara.svg', alt: 'Lengthening Mascara', isPrimary: true }], benefits: ['Volume + Length', 'Smudge-proof'], ingredients: 'Keratin, Argan Oil, Polymers', howToUse: 'Apply from root to tip' },
      { name: 'Moonlight Highlighter', slug: 'moonlight-highlighter', category: 'makeup', description: 'Luminous celestial highlighter', price: 2299, originalPrice: 2799, rating: 4.6, reviewCount: 112, stock: 50, images: [{ url: '/images/products/makeup-highlighter.svg', alt: 'Moonlight Highlighter', isPrimary: true }], benefits: ['Intense glow', 'Blendable'], ingredients: 'Mica, Pearl Powder, Vitamin E', howToUse: 'Apply to high points of face' },
      { name: 'Silk Priming Mist', slug: 'silk-primer', category: 'makeup', description: 'Hydrating makeup primer spray', price: 1599, originalPrice: 1999, badge: 'New', rating: 4.3, reviewCount: 56, stock: 60, images: [{ url: '/images/products/makeup-primer.svg', alt: 'Silk Primer', isPrimary: true }], benefits: ['Smooth base', 'Long-lasting'], ingredients: 'Glycerin, Aloe Vera, Green Tea', howToUse: 'Spray before makeup application' },
      { name: 'Full Coverage Concealer', slug: 'full-coverage-concealer', category: 'makeup', description: 'Full coverage concealer with hyaluronic acid', price: 1999, originalPrice: 2399, rating: 4.5, reviewCount: 89, stock: 70, images: [{ url: '/images/products/makeup-concealer.svg', alt: 'Full Coverage Concealer', isPrimary: true }], benefits: ['Full coverage', 'Hydrating'], ingredients: 'Hyaluronic Acid, Vitamin E', howToUse: 'Apply under eyes and blend' },
      { name: 'Lip Gloss Shine', slug: 'lip-gloss-shine', category: 'makeup', description: 'High shine lip gloss with vitamin E', price: 1299, originalPrice: 1599, badge: 'Sale', rating: 4.2, reviewCount: 63, stock: 90, images: [{ url: '/images/products/makeup-lip-gloss.svg', alt: 'Lip Gloss Shine', isPrimary: true }], benefits: ['High shine', 'Nourishing'], ingredients: 'Vitamin E, Jojoba Oil', howToUse: 'Apply directly to lips' },
      { name: 'Precision Brow Pencil', slug: 'precision-brow-pencil', category: 'makeup', description: 'Ultra-fine brow pencil for precise shaping', price: 999, originalPrice: 1199, rating: 4.4, reviewCount: 78, stock: 80, images: [{ url: '/images/products/makeup-brow.svg', alt: 'Brow Pencil', isPrimary: true }], benefits: ['Precise', 'Natural look'], ingredients: 'Castor Oil, Vitamin E', howToUse: 'Fill in brows with light strokes' },
      { name: 'Makeup Setting Spray', slug: 'setting-spray', category: 'makeup', description: 'Long-lasting makeup setting spray', price: 1499, originalPrice: 1799, rating: 4.6, reviewCount: 92, stock: 55, images: [{ url: '/images/products/makeup-setting-spray.svg', alt: 'Setting Spray', isPrimary: true }], benefits: ['All-day wear', 'Hydrating'], ingredients: 'Aloe Vera, Green Tea, Glycerin', howToUse: 'Spray after makeup application' },
      { name: 'Contour Stick', slug: 'contour-stick', category: 'makeup', description: 'Cream contour stick for sculpting', price: 2199, originalPrice: 2599, badge: 'Best Seller', rating: 4.7, reviewCount: 103, stock: 48, images: [{ url: '/images/products/makeup-contour.svg', alt: 'Contour Stick', isPrimary: true }], benefits: ['Sculpts', 'Blendable'], ingredients: 'Shea Butter, Vitamin E, Pigments', howToUse: 'Apply to hollows of cheeks and blend' },
      // HAIRCARE (10 products)
      { name: 'Silk Hair Elixir', slug: 'silk-hair-elixir', category: 'haircare', description: 'Silky smooth hair with argan and keratin', price: 1999, originalPrice: 2499, rating: 4.7, reviewCount: 56, stock: 42, images: [{ url: '/images/products/haircare-oil.svg', alt: 'Silk Hair Elixir', isPrimary: true }], benefits: ['Silky smooth', 'Reduces frizz'], ingredients: 'Argan Oil, Keratin, Vitamin E', howToUse: 'Apply to damp hair' },
      { name: 'Volumizing Shampoo', slug: 'volumizing-shampoo', category: 'haircare', description: 'Volume-boosting gentle shampoo', price: 1499, originalPrice: 1799, rating: 4.5, reviewCount: 78, stock: 95, images: [{ url: '/images/products/haircare-shampoo.svg', alt: 'Volumizing Shampoo', isPrimary: true }], benefits: ['Adds volume', 'Gentle cleanse'], ingredients: 'Biotin, Keratin, Protein complex', howToUse: 'Massage into scalp and rinse' },
      { name: 'Hydrating Conditioner', slug: 'hydrating-conditioner', category: 'haircare', description: 'Moisturizing detangling conditioner', price: 1599, originalPrice: 1899, rating: 4.4, reviewCount: 52, stock: 88, images: [{ url: '/images/products/haircare-conditioner.svg', alt: 'Hydrating Conditioner', isPrimary: true }], benefits: ['Deep hydration', 'Detangles'], ingredients: 'Shea Butter, Argan Oil, Glycerin', howToUse: 'Apply after shampoo, leave 2 mins' },
      { name: 'Repair Hair Serum', slug: 'repair-hair-serum', category: 'haircare', description: 'Repair and protect hair serum', price: 2199, originalPrice: 2599, badge: 'Best Seller', rating: 4.6, reviewCount: 89, stock: 60, images: [{ url: '/images/products/haircare-serum.svg', alt: 'Repair Hair Serum', isPrimary: true }], benefits: ['Repairs damage', 'Heat protection'], ingredients: 'Argan Oil, Keratin, Silicones', howToUse: 'Apply to damp or dry hair' },
      { name: 'Deep Nourish Hair Mask', slug: 'deep-nourish-hair-mask', category: 'haircare', description: 'Weekly deep conditioning mask', price: 2499, originalPrice: 2899, rating: 4.7, reviewCount: 103, stock: 45, images: [{ url: '/images/products/haircare-mask.svg', alt: 'Deep Nourish Hair Mask', isPrimary: true }], benefits: ['Deep conditioning', 'Repairs damage'], ingredients: 'Avocado Oil, Keratin, Vitamins', howToUse: 'Apply for 15-20 mins, then rinse' },
      { name: 'Shine Hair Spray', slug: 'shine-hair-spray', category: 'haircare', description: 'Luminous finishing hair spray', price: 1299, originalPrice: 1499, rating: 4.3, reviewCount: 41, stock: 70, images: [{ url: '/images/products/haircare-spray.svg', alt: 'Shine Hair Spray', isPrimary: true }], benefits: ['High shine', 'Light hold'], ingredients: 'Silk proteins, UV filters', howToUse: 'Spray 20cm from hair' },
      { name: 'Leave-In Conditioner', slug: 'leave-in-conditioner', category: 'haircare', description: 'Weightless leave-in conditioner with argan oil', price: 1399, originalPrice: 1699, badge: 'New', rating: 4.5, reviewCount: 38, stock: 55, images: [{ url: '/images/products/haircare-leave-in.svg', alt: 'Leave In Conditioner', isPrimary: true }], benefits: ['Detangles', 'Hydrates'], ingredients: 'Argan Oil, Aloe Vera, Vitamin E', howToUse: 'Apply to damp hair, do not rinse' },
      { name: 'Dry Shampoo', slug: 'dry-shampoo', category: 'haircare', description: 'Instant refresh dry shampoo', price: 999, originalPrice: 1199, rating: 4.3, reviewCount: 67, stock: 100, images: [{ url: '/images/products/haircare-dry-shampoo.svg', alt: 'Dry Shampoo', isPrimary: true }], benefits: ['Instant refresh', 'Volume'], ingredients: 'Rice Starch, Kaolin Clay, Fragrance', howToUse: 'Spray on roots and massage' },
      { name: 'Smoothing Hair Cream', slug: 'smoothing-hair-cream', category: 'haircare', description: 'Anti-frizz smoothing hair cream', price: 1799, originalPrice: 2199, rating: 4.4, reviewCount: 45, stock: 50, images: [{ url: '/images/products/haircare-hair-cream.svg', alt: 'Hair Cream', isPrimary: true }], benefits: ['Smooths', 'Anti-frizz'], ingredients: 'Shea Butter, Argan Oil, Silicones', howToUse: 'Apply to damp hair and style' },
      { name: 'Scalp Treatment Serum', slug: 'scalp-treatment', category: 'haircare', description: 'Nourishing scalp treatment for healthy hair', price: 2499, originalPrice: 2999, badge: 'New', rating: 4.6, reviewCount: 34, stock: 30, images: [{ url: '/images/products/haircare-scalp-treatment.svg', alt: 'Scalp Treatment', isPrimary: true }], benefits: ['Healthy scalp', 'Strengthens'], ingredients: 'Tea Tree Oil, Biotin, Peptides', howToUse: 'Apply to scalp and massage' },
      // FRAGRANCE (10 products)
      { name: 'Rose Petal Mist', slug: 'rose-petal-mist', category: 'fragrance', description: 'Instant hydration with rose water', price: 1299, originalPrice: 1499, rating: 4.5, reviewCount: 34, stock: 65, images: [{ url: '/images/products/fragrance-mist.svg', alt: 'Rose Petal Mist', isPrimary: true }], benefits: ['Refreshing', 'Sets makeup'], ingredients: 'Rose Water, Glycerin', howToUse: 'Spray on face or body' },
      { name: 'Midnight Oud Perfume', slug: 'midnight-oud-perfume', category: 'fragrance', description: 'Elegant oud fragrance for evening', price: 5499, originalPrice: 6499, badge: 'Exclusive', rating: 4.8, reviewCount: 167, stock: 25, images: [{ url: '/images/products/fragrance-perfume.svg', alt: 'Midnight Oud Perfume', isPrimary: true }], benefits: ['Long-lasting', 'Luxury scent'], ingredients: 'Oud, Rose, Amber, Musk', howToUse: 'Spray on pulse points' },
      { name: 'Vanilla Dream Spray', slug: 'vanilla-dream-spray', category: 'fragrance', description: 'Sweet vanilla body mist', price: 1599, originalPrice: 1899, rating: 4.4, reviewCount: 82, stock: 58, images: [{ url: '/images/products/fragrance-body-spray.svg', alt: 'Vanilla Dream Spray', isPrimary: true }], benefits: ['Sweet scent', 'Long-lasting'], ingredients: 'Vanilla, Jasmine, Musk', howToUse: 'Spray all over body' },
      { name: 'Fresh Citrus Deodorant', slug: 'fresh-citrus-deodorant', category: 'fragrance', description: 'Refreshing citrus deodorant', price: 999, originalPrice: 1199, rating: 4.3, reviewCount: 45, stock: 110, images: [{ url: '/images/products/fragrance-deodorant.svg', alt: 'Fresh Citrus Deodorant', isPrimary: true }], benefits: ['24hr protection', 'Refreshing'], ingredients: 'Citrus extracts, Aluminum-free', howToUse: 'Apply to clean underarms' },
      { name: 'Rose Gold Candle', slug: 'rose-gold-candle', category: 'fragrance', description: 'Luxurious rose gold candle', price: 1899, originalPrice: 2299, rating: 4.6, reviewCount: 73, stock: 35, images: [{ url: '/images/products/fragrance-candle.svg', alt: 'Rose Gold Candle', isPrimary: true }], benefits: ['40hr burn time', 'Luxury scent'], ingredients: 'Soy wax, Rose & Oud fragrance', howToUse: 'Burn 2-3 hours at a time' },
      { name: 'Luxury Gift Set', slug: 'luxury-gift-set', category: 'fragrance', description: 'Premium fragrance gift collection', price: 4999, originalPrice: 5999, badge: 'Sale', rating: 4.7, reviewCount: 91, stock: 20, images: [{ url: '/images/products/fragrance-gift-set.svg', alt: 'Luxury Gift Set', isPrimary: true }], benefits: ['5pc set', 'Perfect gift'], ingredients: 'Mixed fragrances', howToUse: 'Follow individual product instructions' },
      { name: 'Rose Intense EDP', slug: 'rose-intense-edp', category: 'fragrance', description: 'Intense rose perfume with musk notes', price: 3999, originalPrice: 4999, badge: 'Best Seller', rating: 4.7, reviewCount: 134, stock: 40, images: [{ url: '/images/products/fragrance-rose-perfume.svg', alt: 'Rose Intense EDP', isPrimary: true }], benefits: ['Intense scent', 'Long-lasting'], ingredients: 'Rose, Musk, Amber', howToUse: 'Spray on pulse points' },
      { name: 'Premium Oud Oil Roll-On', slug: 'premium-oud-oil', category: 'fragrance', description: 'Concentrated oud perfume oil roll-on', price: 2999, originalPrice: 3599, rating: 4.5, reviewCount: 67, stock: 50, images: [{ url: '/images/products/fragrance-oud-oil.svg', alt: 'Oud Oil', isPrimary: true }], benefits: ['Concentrated', 'Travel-friendly'], ingredients: 'Oud Oil, Sandalwood, Musk', howToUse: 'Apply to pulse points' },
      { name: 'Lavender Relax Mist', slug: 'lavender-mist', category: 'fragrance', description: 'Calming lavender body and room mist', price: 1199, originalPrice: 1399, rating: 4.4, reviewCount: 45, stock: 75, images: [{ url: '/images/products/fragrance-lavender.svg', alt: 'Lavender Mist', isPrimary: true }], benefits: ['Calming', 'Aromatherapy'], ingredients: 'Lavender Oil, Distilled Water', howToUse: 'Spray on body or room' },
      { name: 'Jasmine Bloom Spray', slug: 'jasmine-spray', category: 'fragrance', description: 'Fresh jasmine flower body spray', price: 1799, originalPrice: 2199, badge: 'New', rating: 4.6, reviewCount: 56, stock: 60, images: [{ url: '/images/products/fragrance-jasmine.svg', alt: 'Jasmine Spray', isPrimary: true }], benefits: ['Floral scent', 'All-day fresh'], ingredients: 'Jasmine Extract, Alcohol, Water', howToUse: 'Spray on body' },
      // BODY CARE (10 products)
      { name: 'Luxe Body Lotion', slug: 'luxe-body-lotion', category: 'body-care', description: 'Soft, smooth skin with shea butter', price: 1799, originalPrice: 2199, badge: 'Sale', rating: 4.4, reviewCount: 67, stock: 72, images: [{ url: '/images/products/body-care-lotion.svg', alt: 'Luxe Body Lotion', isPrimary: true }], benefits: ['Deep hydration', 'Non-greasy'], ingredients: 'Shea Butter, Cocoa Butter, Vitamin E', howToUse: 'Apply to body after shower' },
      { name: 'Rose Sugar Scrub', slug: 'rose-sugar-scrub', category: 'body-care', description: 'Gentle exfoliating sugar scrub', price: 1499, originalPrice: 1799, rating: 4.5, reviewCount: 54, stock: 48, images: [{ url: '/images/products/body-care-scrub.svg', alt: 'Rose Sugar Scrub', isPrimary: true }], benefits: ['Exfoliates', 'Hydrates'], ingredients: 'Sugar, Rose Oil, Almond Oil', howToUse: 'Use 2-3 times weekly' },
      { name: 'Shea Body Butter', slug: 'shea-body-butter', category: 'body-care', description: 'Intensive moisturizing body butter', price: 2199, originalPrice: 2599, rating: 4.6, reviewCount: 78, stock: 40, images: [{ url: '/images/products/body-care-butter.svg', alt: 'Shea Body Butter', isPrimary: true }], benefits: ['Intense moisture', 'Repairs dry skin'], ingredients: 'Shea Butter, Mango Butter, Coconut Oil', howToUse: 'Apply to dry areas' },
      { name: 'Relaxing Body Oil', slug: 'relaxing-body-oil', category: 'body-care', description: 'Relaxing lavender body oil', price: 1999, originalPrice: 2299, rating: 4.5, reviewCount: 62, stock: 55, images: [{ url: '/images/products/body-care-oil.svg', alt: 'Relaxing Body Oil', isPrimary: true }], benefits: ['Relaxing scent', 'Nourishes'], ingredients: 'Lavender Oil, Almond Oil, Vitamin E', howToUse: 'Apply after shower on damp skin' },
      { name: 'Artisan Soap Bar', slug: 'artisan-soap-bar', category: 'body-care', description: 'Natural handcrafted soap bar', price: 799, originalPrice: 999, rating: 4.3, reviewCount: 41, stock: 120, images: [{ url: '/images/products/body-care-soap.svg', alt: 'Artisan Soap Bar', isPrimary: true }], benefits: ['Natural', 'Gentle cleanse'], ingredients: 'Olive Oil, Coconut Oil, Essential oils', howToUse: 'Lather and rinse' },
      { name: 'Hand Cream', slug: 'hand-cream', category: 'body-care', description: 'Moisturizing hand cream', price: 899, originalPrice: 1099, rating: 4.4, reviewCount: 38, stock: 95, images: [{ url: '/images/products/body-care-cream.svg', alt: 'Hand Cream', isPrimary: true }], benefits: ['Deep hydration', 'Fast absorbing'], ingredients: 'Shea Butter, Glycerin, Vitamin E', howToUse: 'Apply as needed' },
      { name: 'Luxe Shower Gel', slug: 'luxe-shower-gel', category: 'body-care', description: 'Luxurious moisturizing shower gel', price: 1299, originalPrice: 1599, badge: 'Sale', rating: 4.4, reviewCount: 56, stock: 80, images: [{ url: '/images/products/body-care-shower-gel.svg', alt: 'Luxe Shower Gel', isPrimary: true }], benefits: ['Moisturizes', 'Aromatherapy'], ingredients: 'Aloe Vera, Glycerin, Essential Oils', howToUse: 'Apply to wet skin and rinse' },
      { name: 'Rose Bath Bomb Set', slug: 'rose-bath-bomb', category: 'body-care', description: 'Fizzing rose scented bath bombs', price: 999, originalPrice: 1299, rating: 4.5, reviewCount: 73, stock: 65, images: [{ url: '/images/products/body-care-bath-bomb.svg', alt: 'Rose Bath Bomb', isPrimary: true }], benefits: ['Relaxing', 'Scented'], ingredients: 'Baking Soda, Citric Acid, Rose Oil', howToUse: 'Drop in warm bath' },
      { name: 'Cooling Foot Cream', slug: 'cooling-foot-cream', category: 'body-care', description: 'Refreshing foot cream with peppermint', price: 899, originalPrice: 1099, rating: 4.3, reviewCount: 34, stock: 75, images: [{ url: '/images/products/body-care-foot-cream.svg', alt: 'Foot Cream', isPrimary: true }], benefits: ['Cooling', 'Refreshes'], ingredients: 'Peppermint Oil, Shea Butter, Urea', howToUse: 'Apply to clean feet' },
      { name: 'Relaxing Massage Oil', slug: 'massage-oil', category: 'body-care', description: 'Warm massage oil for relaxation', price: 1699, originalPrice: 1999, rating: 4.5, reviewCount: 47, stock: 50, images: [{ url: '/images/products/body-care-massage-oil.svg', alt: 'Massage Oil', isPrimary: true }], benefits: ['Relaxing', 'Nourishes'], ingredients: 'Jojoba Oil, Lavender Oil, Vitamin E', howToUse: 'Warm and massage into skin' },
    ];

    // Products already carry their correct per-category local image URLs
    // (set inline above). Do NOT overwrite them with a single generic image.

    let created = 0;
    let updated = 0;

    for (const product of products) {
      const result = await Product.findOneAndUpdate(
        { slug: product.slug },
        { ...product, isActive: true },
        { upsert: true, new: true }
      );
      if (result.createdAt && result.updatedAt && result.createdAt.getTime() === result.updatedAt.getTime()) {
        created++;
      } else {
        updated++;
      }
    }

    // Update category product counts
    for (const cat of categories) {
      const count = await Product.countDocuments({ category: cat.slug, isActive: true });
      await Category.findOneAndUpdate({ slug: cat.slug }, { productCount: count });
    }

    return Response.json({
      success: true,
      message: `Database seeded successfully! Created: ${created}, Updated: ${updated}`,
      totalProducts: products.length,
    });
  } catch (error) {
    return Response.json({ success: false, error: error.message }, { status: 500 });
  }
}

